# Generated by Django 5.2.17 on 2026-09-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PmvAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm')),
                ('kind', models.CharField(choices=[('READ', 'Đọc'), ('ADMIN', 'Quản trị (backup/tiện ích)'), ('BLOCKED', 'CHẶN — vượt quyền'), ('CANHBAO', 'Cảnh báo')], db_index=True, max_length=10, verbose_name='Loại')),
                ('tag', models.CharField(max_length=100, verbose_name='Nghiệp vụ gọi')),
                ('summary', models.CharField(max_length=500, verbose_name='Lệnh/tóm tắt')),
                ('ok', models.BooleanField(default=True, verbose_name='Thành công')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='Thời lượng (ms)')),
                ('error', models.TextField(blank=True, default='', verbose_name='Lỗi')),
            ],
            options={
                'verbose_name': 'Nhật ký PMV',
                'verbose_name_plural': 'Nhật ký PMV',
                'db_table': 'pmv_audit_logs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PmvState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trạng thái PMV',
                'verbose_name_plural': 'Trạng thái PMV',
                'db_table': 'pmv_state',
            },
        ),
    ]
