# Generated by Django 5.2.17 on 2026-09-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmvSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Nhãn')),
                ('source', models.CharField(choices=[('pmv', 'PMV thật'), ('sandbox', 'Sandbox')], max_length=10, verbose_name='Nguồn')),
                ('mode', models.CharField(default='fast', max_length=8, verbose_name='Mức')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table_count', models.IntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Snapshot PMV',
                'verbose_name_plural': 'Snapshot PMV',
                'db_table': 'pmv_snapshots',
                'ordering': ['-id'],
            },
        ),
    ]
