# Generated by Django 5.2.17 on 2026-09-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmv', '0002_pmvsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmvBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(db_index=True, verbose_name='Thời điểm (giờ KK)')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('STATS', 'Thống kê (bộ đếm SQL)'), ('TRACE', 'Trace (từng lời gọi + tham số)')], db_index=True, max_length=6)),
                ('category', models.CharField(db_index=True, max_length=30, verbose_name='Nhóm')),
                ('action', models.CharField(max_length=10, verbose_name='Hành động')),
                ('proc_name', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('text', models.TextField(blank=True, default='', verbose_name='Lệnh + tham số')),
                ('login', models.CharField(blank=True, default='', max_length=64)),
                ('host', models.CharField(blank=True, default='', max_length=64)),
                ('app', models.CharField(blank=True, default='', max_length=128)),
                ('spid', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('reads', models.IntegerField(blank=True, null=True)),
                ('writes', models.IntegerField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('exec_delta', models.IntegerField(blank=True, null=True, verbose_name='Số lần gọi thêm')),
                ('event_seq', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hành vi PMV',
                'verbose_name_plural': 'Hành vi PMV',
                'db_table': 'pmv_behavior_logs',
                'ordering': ['-event_time', '-id'],
            },
        ),
    ]
