# Generated by Django 5.2.17 on 2026-09-02 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmv', '0003_pmvbehavior'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmvaudit',
            name='kind',
            field=models.CharField(choices=[('READ', 'Đọc'), ('EXEC', 'Gọi proc'), ('ADMIN', 'Quản trị (backup/tiện ích)'), ('BLOCKED', 'CHẶN — vượt quyền'), ('CANHBAO', 'Cảnh báo')], db_index=True, max_length=10, verbose_name='Loại'),
        ),
        migrations.CreateModel(
            name='PmvUser',
            fields=[
                ('user_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='UserID')),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name='UserName')),
                ('password', models.CharField(blank=True, default='', max_length=128, verbose_name='Password (băm)')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='FirstName')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='LastName')),
                ('full_name', models.CharField(blank=True, default='', max_length=200, verbose_name='FullName')),
                ('is_admin', models.CharField(default='0', max_length=1, verbose_name='IsAdmin')),
                ('active', models.CharField(default='1', max_length=1, verbose_name='Active')),
                ('shop_id', models.CharField(blank=True, default='', max_length=15, verbose_name='ShopID')),
                ('emp_id', models.CharField(blank=True, default='', max_length=15, verbose_name='EmpID')),
                ('till_id', models.CharField(blank=True, default='', max_length=15, verbose_name='TillID (két của user — proc bán cần)')),
                ('till_code', models.CharField(blank=True, default='', max_length=50, verbose_name='TillCode')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('django_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmv_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tài khoản PMV (bản sao)',
                'verbose_name_plural': 'Tài khoản PMV (bản sao)',
                'db_table': 'sys_users',
            },
        ),
    ]
