# Generated by Django 5.2.17 on 2026-09-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmv', '0004_alter_pmvaudit_kind_pmvuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmvChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(db_index=True, verbose_name='Từ')),
                ('window_end', models.DateTimeField(verbose_name='Đến')),
                ('table', models.CharField(db_index=True, max_length=128, verbose_name='Bảng')),
                ('rows_before', models.IntegerField(blank=True, null=True)),
                ('rows_after', models.IntegerField(blank=True, null=True)),
                ('delta', models.IntegerField(blank=True, null=True)),
                ('cs_changed', models.BooleanField(default=False, verbose_name='Checksum đổi')),
                ('procs', models.TextField(blank=True, default='', verbose_name='Proc ghi trong khung')),
                ('mark', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thay đổi SQL KK',
                'verbose_name_plural': 'Thay đổi SQL KK',
                'db_table': 'pmv_change_logs',
                'ordering': ['-id'],
            },
        ),
    ]
