# Generated by Django 5.2.17 on 2026-09-04 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmv', '0005_pmvchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmvProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=150, verbose_name='Tên quy trình')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp (mới học)'), ('approved', 'GĐ đã duyệt')], default='draft', max_length=10)),
                ('version', models.IntegerField(default=1)),
                ('source', models.TextField(blank=True, default='', verbose_name='Nguồn học (hóa đơn/khung giờ đo)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quy trình PMV',
                'verbose_name_plural': 'Quy trình PMV',
                'db_table': 'pmv_process',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PmvProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=150, verbose_name='Tên pha / bước')),
                ('proc_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Proc')),
                ('action', models.CharField(blank=True, default='', max_length=10, verbose_name='ghi/đọc')),
                ('repeat', models.BooleanField(default=False, verbose_name='Lặp nhiều lần (×N)')),
                ('params', models.TextField(blank=True, default='', verbose_name='Tham số quan trọng')),
                ('tables', models.TextField(blank=True, default='', verbose_name='Bảng đổi')),
                ('khbl', models.CharField(choices=[('lam', 'KHBL thực hiện'), ('kiem', 'Cần kiểm trên sandbox'), ('rieng', 'KHBL làm cách riêng'), ('bo', 'Ngoài phạm vi — bỏ')], default='lam', max_length=10)),
                ('doi_chieu', models.CharField(choices=[('chua', 'Chưa đối chiếu'), ('khop', 'Khớp app'), ('lech', 'Lệch app')], default='chua', max_length=10)),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pmv.pmvprocessstep')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pmv.pmvprocess')),
            ],
            options={
                'verbose_name': 'Bước quy trình',
                'verbose_name_plural': 'Bước quy trình',
                'db_table': 'pmv_process_step',
                'ordering': ['process', 'parent_id', 'order', 'id'],
            },
        ),
    ]
