# Generated by Django 5.2.17 on 2026-09-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmv', '0009_pmvwebuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoduleaccess',
            name='module',
            field=models.CharField(choices=[('DASHBOARD', 'Tổng quan'), ('BAN_HANG', 'Bán hàng'), ('THAU_VAO', 'Thâu vào'), ('BANG_GIA', 'Bảng giá'), ('KHACH_HANG', 'Khách hàng'), ('HOA_DON', 'Hóa đơn'), ('DAT_COC', 'Đặt cọc'), ('HE_THONG', 'Hệ thống')], max_length=20),
        ),
    ]
