# -*- coding: utf-8 -*-
"""MIGRATION RỖNG CÓ CHỦ Ý — 3 bảng zalo_* là BẢN CHÉP TỪ CARE360, Django KHÔNG SỞ HỮU.

Cả ba model khai ``managed = False`` nên migration này KHÔNG sinh một câu DDL nào
(kiểm chứng: ``manage.py sqlmigrate oa 0001`` in ra "(no-op)" cho cả 3 CreateModel).
Nó chỉ ghi TRẠNG THÁI để ``makemigrations --check`` sạch và để app có lịch sử migration.

⚠ BA MIGRATION CŨ ĐÃ BỊ XÓA (14/09/2026) VÌ LÀ MÌN HẸN GIỜ: ``0001_initial`` cũ
``CreateModel`` với ``db_table`` trùng đúng tên 3 bảng đang có 16.657 dòng thật, ``0002`` seed dữ
liệu theo bộ cột CŨ, ``0003`` ``AddConstraint`` + vá khóa rỗng GHI THẲNG vào bảng thật. Lần
``manage.py migrate`` kế tiếp bất kỳ (KHBL còn nhiều app khác) sẽ đâm lỗi 1050 chặn cả hàng đợi
migration, và ai gỡ kẹt bằng ``--fake 0001`` thì ``0003`` sẽ ALTER bảng thật.

⚠ KHÔNG BAO GIỜ bỏ ``managed = False`` trong ``apps/oa/models.py``: bỏ là lần makemigrations sau
sinh DDL cho ba bảng này.
"""
# Generated by Django 5.2.17 on 2026-09-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZaloMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('campaign_id', models.BigIntegerField(blank=True, null=True)),
                ('oa_account_id', models.BigIntegerField()),
                ('external_template_id', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=20)),
                ('source_type', models.CharField(max_length=30)),
                ('source_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('trn_id', models.CharField(blank=True, max_length=30, null=True)),
                ('bill_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('emp_id', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('shop_id', models.CharField(blank=True, max_length=30, null=True)),
                ('till_id', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_at', models.DateTimeField(blank=True, null=True)),
                ('eligible_at', models.DateTimeField(blank=True, null=True)),
                ('source_status', models.CharField(blank=True, max_length=10, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('source_eligible', models.BooleanField(default=True)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('recipient_ciphertext', models.TextField()),
                ('recipient_masked', models.CharField(max_length=40)),
                ('recipient_hash', models.CharField(max_length=64)),
                ('template_data_json', models.TextField()),
                ('tracking_id', models.CharField(max_length=48, unique=True)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('msg_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=40, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('sending_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('paid_cost', models.CharField(blank=True, max_length=11, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('rule_snapshot_json', models.TextField(blank=True, null=True)),
                ('response_json', models.TextField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Tin ZNS',
                'verbose_name_plural': 'Tin ZNS',
                'db_table': 'zalo_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZaloSendRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(blank=True, max_length=99, null=True)),
                ('oa_account_id', models.BigIntegerField()),
                ('message_group', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('cooldown_minutes', models.IntegerField(default=0)),
                ('cooldown_scope', models.CharField(max_length=30)),
                ('apply_to_manual_messages', models.BooleanField(default=False)),
                ('scan_lookback_minutes', models.IntegerField(default=0)),
                ('daily_message_limit', models.IntegerField(blank=True, null=True)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_attempts', models.IntegerField(default=0)),
                ('retry_base_minutes', models.IntegerField(default=0)),
                ('send_time_from', models.TimeField(blank=True, null=True)),
                ('send_time_to', models.TimeField(blank=True, null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('options_json', models.TextField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Quy tắc gửi ZNS',
                'verbose_name_plural': 'Quy tắc gửi ZNS',
                'db_table': 'zalo_send_rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZaloTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('oa_account_id', models.BigIntegerField()),
                ('template_id', models.CharField(max_length=100)),
                ('template_name', models.CharField(max_length=250)),
                ('template_type', models.CharField(blank=True, max_length=50, null=True)),
                ('template_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=40)),
                ('quality', models.CharField(max_length=30)),
                ('price_sdt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_uid', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('preview_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('params_json', models.TextField(blank=True, null=True)),
                ('layout_json', models.TextField(blank=True, null=True)),
                ('raw_json', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('zalo_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Mẫu ZNS',
                'verbose_name_plural': 'Mẫu ZNS',
                'db_table': 'zalo_templates',
                'managed': False,
            },
        ),
    ]
