# Generated by Django 5.2.17 on 2026-09-05 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_type', models.CharField(max_length=50, unique=True)),
                ('pinned', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'gold_price_display',
                'ordering': ['position', 'gold_type'],
            },
        ),
        migrations.CreateModel(
            name='PriceBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=10)),
                ('payload', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gold_price_batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
