# Generated by Django 5.2.17 on 2026-09-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedisplay',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
