# Generated by Django 5.2.17 on 2026-09-07 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_unlock_passcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn_id', models.CharField(db_index=True, max_length=20)),
                ('bill_code', models.CharField(blank=True, default='', max_length=30)),
                ('action', models.CharField(max_length=10)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('version', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bill_audit',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
