# Generated by Django 5.2.17 on 2026-09-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_bill_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn_id', models.CharField(max_length=20, unique=True)),
                ('bill_code', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('trn_date', models.DateField(blank=True, db_index=True, null=True)),
                ('trn_time', models.CharField(blank=True, default='', max_length=8)),
                ('nguon', models.CharField(default='KHBL', max_length=8)),
                ('emp_id', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('emp_sup_id', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='NV hỗ trợ')),
                ('cust_id', models.CharField(blank=True, default='', max_length=20)),
                ('cust_name', models.CharField(blank=True, default='', max_length=200)),
                ('cust_phone', models.CharField(blank=True, default='', max_length=30)),
                ('user_web', models.CharField(blank=True, default='', max_length=150)),
                ('tien_vang_moi', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('tien_vang_cu', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('tien_vang_them', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('tien_cong_them', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('tien_bot', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('tien_coc', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('tong', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Khách trả (PayAmount)')),
                ('pay_method', models.CharField(default='cash', max_length=8)),
                ('tien_mat', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('tien_ck', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('tien_the', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('bank_id', models.CharField(blank=True, default='', max_length=20)),
                ('items', models.JSONField(blank=True, default=list)),
                ('doi', models.JSONField(blank=True, default=list)),
                ('ma_sp', models.TextField(blank=True, default='')),
                ('status', models.CharField(db_index=True, default='W', max_length=2)),
                ('is_del', models.BooleanField(default=False)),
                ('kk_upd', models.CharField(blank=True, default='', max_length=40, verbose_name='TrnDateTime_Upd lúc đồng bộ')),
                ('so_lan_in', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gold_bill',
                'ordering': ['-trn_date', '-trn_time'],
            },
        ),
    ]
