# Generated by Django 5.2.17 on 2026-09-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_thau_nhom'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconcileState',
            fields=[
                ('notification_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('trn_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('fingerprint', models.CharField(default='', max_length=64)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bank_reconcile_state',
            },
        ),
    ]
