# Generated by Django 5.2.17 on 2026-09-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_thau_anh'),
        ('pos', '0008_bank_reconcile_index'),
    ]

    operations = [
    ]
