# Generated by Django 5.2.17 on 2026-09-09 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_thau_nhom_ck_ten'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThauPaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.CharField(db_index=True, max_length=64)),
                ('trn_ids', models.JSONField(default=list)),
                ('notification_id', models.BigIntegerField(db_index=True)),
                ('active_notification_id', models.BigIntegerField(null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('snapshot', models.JSONField(default=dict)),
                ('bank_snapshot', models.JSONField(default=dict)),
                ('mode', models.CharField(max_length=10)),
                ('username', models.CharField(default='', max_length=150)),
                ('reason', models.CharField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('revoked_by', models.CharField(default='', max_length=150)),
                ('revoke_reason', models.CharField(default='', max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thau_payment_link',
            },
        ),
    ]
