# Generated by Django 5.2.17 on 2026-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_thau_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='thaunhom',
            name='anh_hinh1',
            field=models.BinaryField(blank=True, null=True, verbose_name='Hình 1'),
        ),
        migrations.AddField(
            model_name='thaunhom',
            name='anh_hinh2',
            field=models.BinaryField(blank=True, null=True, verbose_name='Hình 2'),
        ),
        migrations.AddField(
            model_name='thaunhom',
            name='anh_qr',
            field=models.BinaryField(blank=True, null=True, verbose_name='QR chuyển khoản'),
        ),
    ]
