# Generated by Django 5.2.17 on 2026-09-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_depositsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositsubmission',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
