# Generated by Django 5.2.17 on 2026-09-11 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_alter_depositsubmission_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=10)),
                ('trn_id', models.CharField(db_index=True, max_length=20)),
                ('action', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=150)),
                ('note', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider_id', models.CharField(blank=True, max_length=80)),
                ('body', models.TextField()),
                ('approved_body_hash', models.CharField(blank=True, max_length=64)),
                ('parameter_map', models.JSONField(default=dict)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositMoneyOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=10)),
                ('trn_id', models.CharField(db_index=True, max_length=20)),
                ('kind', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('cash', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('bank', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('invoice_id', models.CharField(blank=True, max_length=20)),
                ('bank_key', models.CharField(max_length=60, null=True, unique=True)),
                ('status', models.CharField(db_index=True, default='queued', max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(max_length=20)),
                ('till_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=150)),
                ('evidence', models.JSONField(default=dict)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositStockHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=10)),
                ('trn_id', models.CharField(db_index=True, max_length=20)),
                ('product_code', models.CharField(max_length=80)),
                ('active_key', models.CharField(max_length=100, null=True, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(null=True)),
                ('released_by', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DepositMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=10)),
                ('trn_id', models.CharField(db_index=True, max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('template_version', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('parameters', models.JSONField(default=dict)),
                ('purpose', models.CharField(default='ready', max_length=20)),
                ('planned_day', models.DateField(db_index=True)),
                ('scheduled_at', models.DateTimeField(db_index=True, null=True)),
                ('status', models.CharField(db_index=True, default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=0)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dedupe_key', models.CharField(max_length=64, null=True, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('provider_message_id', models.CharField(blank=True, max_length=150)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.depositmessagetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOrderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=10)),
                ('trn_id', models.CharField(max_length=20)),
                ('version', models.PositiveIntegerField(default=0)),
                ('original_promise', models.DateField(blank=True, null=True)),
                ('promise', models.DateField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=20)),
                ('employee_name', models.CharField(blank=True, max_length=200)),
                ('fulfilment', models.CharField(blank=True, max_length=20)),
                ('items', models.JSONField(default=list)),
                ('item_signature', models.CharField(blank=True, max_length=64)),
                ('next_contact', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('contacted', models.BooleanField(null=True)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('quote_status', models.CharField(default='estimate', max_length=12)),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('quote_terms', models.CharField(blank=True, max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target', 'trn_id'), name='dc_state_target_order')],
            },
        ),
    ]
