# Generated by Django 5.2.17 on 2026-09-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_deposit_draft_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositmoneyoperation',
            name='active_key',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
