# Generated by Django 5.2.17 on 2026-09-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_deposit_money_active_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositorderstate',
            name='payment_plan',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='depositorderstate',
            name='pricing',
            field=models.JSONField(default=dict),
        ),
    ]
