# Generated by Django 5.2.17 on 2026-09-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_deposit_editor_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositorderstate',
            name='photos',
            field=models.JSONField(default=dict),
        ),
    ]
