# Generated by Django 5.2.17 on 2026-09-12 09:50

from django.db import migrations, models


def move_deposit_state(apps, schema_editor):
    State = apps.get_model('pos', 'DepositOrderState')
    Bill = apps.get_model('pos', 'GoldBill')
    alias = schema_editor.connection.alias
    for state in State.objects.using(alias).all().iterator():
        values = {field.name: getattr(state, field.name) for field in State._meta.fields
                  if field.name not in ('id', 'target', 'trn_id')}
        old = Bill.objects.using(alias).filter(target=state.target, trn_id=state.trn_id).first()
        if old and old.bill_kind != 'deposit':
            raise RuntimeError('Mã phiếu cọc trùng chứng từ khác trong gold_bill: ' + state.trn_id)
        row, _ = Bill.objects.using(alias).update_or_create(
            target=state.target, trn_id=state.trn_id,
            defaults={**values, 'bill_kind': 'deposit', 'nguon': 'KHBL'})
        Bill.objects.using(alias).filter(pk=row.pk).update(updated_at=state.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_gold_prices_transactional'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldbill',
            name='bill_kind',
            field=models.CharField(db_index=True, default='retail', max_length=12),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='cancellation_policy',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='contacted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='employee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='extra_notes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='fulfilment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='item_signature',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='last_contact',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='next_contact',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='original_promise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='payment_plan',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='photos',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='pricing',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='promise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='quote_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='quote_status',
            field=models.CharField(default='estimate', max_length=12),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='quote_terms',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='target',
            field=models.CharField(default='kk', max_length=10),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goldbill',
            name='trn_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='goldbill',
            constraint=models.UniqueConstraint(fields=('target', 'trn_id'), name='gold_bill_target_trn'),
        ),
        migrations.RunPython(move_deposit_state, migrations.RunPython.noop),
        # Giữ nguyên bảng cũ làm bản đối chiếu; runtime chỉ dùng proxy trên gold_bill.
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.DeleteModel(name='DepositOrderState'),
        ], database_operations=[]),
        migrations.CreateModel(
            name='DepositOrderState',
            fields=[
            ],
            options={
                'ordering': ['-updated_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pos.goldbill',),
        ),
    ]
