# Generated by Django 5.2.17 on 2026-09-12 09:51

from django.db import migrations, models
from django.conf import settings
from pathlib import Path


def copy_photos(apps, schema_editor):
    Bill = apps.get_model('pos', 'GoldBill')
    root = (Path(settings.BASE_DIR) / 'media' / 'datcoc').resolve()
    for row in Bill.objects.using(schema_editor.connection.alias).filter(bill_kind='deposit').iterator():
        photos = dict(row.photos)
        updates = {}
        for slot in ('sample1', 'sample2', 'finished1', 'finished2'):
            name = photos.get(slot)
            if not name or name == 'db':
                continue
            path = (root / name).resolve()
            if not path.is_relative_to(root):
                raise RuntimeError('Đường dẫn ảnh cọc nằm ngoài thư mục cho phép')
            if not path.is_file():
                continue  # Giữ tham chiếu cũ để đối soát, không xóa dấu vết ảnh thiếu.
            updates['dc_photo_' + slot] = path.read_bytes()
            photos[slot] = 'db'
        if updates:
            Bill.objects.using(schema_editor.connection.alias).filter(pk=row.pk).update(**updates, photos=photos)


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_deposit_gold_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldbill',
            name='dc_photo_finished1',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='dc_photo_finished2',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='dc_photo_sample1',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldbill',
            name='dc_photo_sample2',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.RunPython(copy_photos, migrations.RunPython.noop),
    ]
