# Generated by Django 5.2.17 on 2026-09-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_deposit_photo_blobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSyncReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=12)),
                ('source_id', models.PositiveBigIntegerField()),
                ('phone', models.CharField(max_length=30)),
                ('fingerprint', models.CharField(max_length=64)),
                ('cust_id', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(default='writing', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('user_id', models.PositiveBigIntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_sync_receipt',
                'constraints': [models.UniqueConstraint(fields=('target', 'source_id'), name='customer_sync_source_unique')],
            },
        ),
    ]
