# Generated by Django 5.2.17 on 2026-09-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_customersyncreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBridgeReceipt',
            fields=[
                ('token', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=12)),
                ('user_id', models.PositiveBigIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('cust_id', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(default='writing', max_length=16)),
                ('result', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_bridge_receipt',
            },
        ),
    ]
