# Generated by Django 5.2.17 on 2026-09-16 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0029_money_flow_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyflowpayment',
            name='received_before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='MoneyFlowBankReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.BigIntegerField(unique=True)),
                ('bank_identity', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_receipts', to='pos.moneyflow')),
            ],
            options={
                'db_table': 'money_flow_bank_receipt',
            },
        ),
    ]
