# Generated by Django 5.2.17 on 2026-09-17 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0030_money_flow_bank_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyFlowSourceWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_key', models.CharField(max_length=80, null=True, unique=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=12)),
                ('expected', models.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=3, max_digits=18)),
                ('bank', models.DecimalField(decimal_places=3, max_digits=18)),
                ('cash', models.DecimalField(decimal_places=3, max_digits=18)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'money_flow_source_write',
            },
        ),
        migrations.RemoveConstraint(
            model_name='moneyflowpayment',
            name='money_flow_payment_method',
        ),
        migrations.AddField(
            model_name='moneyflowbankreceipt',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moneyflowbankreceipt',
            name='bank_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moneyflowbankreceipt',
            name='bill_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='moneyflowbankreceipt',
            name='direction',
            field=models.CharField(default='IN', max_length=3),
        ),
        migrations.AddField(
            model_name='moneyflowbankreceipt',
            name='source_system',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='moneyflowbankreceipt',
            name='status',
            field=models.CharField(db_index=True, default='applied', max_length=12),
        ),
        migrations.AddField(
            model_name='moneyflowpayment',
            name='active_key',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='moneyflowpayment',
            name='qr_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='moneyflowpayment',
            name='status',
            field=models.CharField(choices=[('ready', 'Sẵn sàng thanh toán'), ('cancelled', 'Đã hủy'), ('success', 'Đã xác minh'), ('superseded', 'Đã thay thế')], db_index=True, default='ready', max_length=12),
        ),
        migrations.AddField(
            model_name='moneyflowsourcewrite',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.moneyflow'),
        ),
    ]
