# Generated by Django 5.2.17 on 2026-09-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_mobile_employee_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileemployeeidentity',
            name='employee_pmv',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='mobileemployeeidentity',
            name='mobile_only',
            field=models.BooleanField(default=True),
        ),
    ]
