# Generated by Django 5.2.17 on 2026-09-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0036_thau_nhom_nghiep_vu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentContactWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('source_type', models.CharField(max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('target', models.CharField(max_length=32)),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_contact_writes',
            },
        ),
        migrations.CreateModel(
            name='DocumentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=32)),
                ('source_id', models.CharField(max_length=100)),
                ('document_code', models.CharField(blank=True, max_length=100)),
                ('cust_id', models.CharField(blank=True, max_length=55)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'document_contacts',
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id'), name='document_contact_source_uniq')],
            },
        ),
    ]
