# Generated by Django 5.2.17 on 2026-09-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0037_document_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcontactwrite',
            name='active_key',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
    ]
