# Generated by Django 5.2.17 on 2026-09-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0038_document_contact_lock'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentcontactwrite',
            index=models.Index(fields=['source_type', 'source_id', 'status'], name='contact_write_source_idx'),
        ),
    ]
