# Generated by Django 5.2.17 on 2026-09-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0039_document_contact_lookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn_id', models.CharField(max_length=20, unique=True)),
                ('bill_code', models.CharField(db_index=True, max_length=30)),
                ('ngay', models.DateField(db_index=True, verbose_name='Ngày làm việc (CreatedDate KK)')),
                ('lap_luc', models.DateTimeField(blank=True, null=True, verbose_name='Giờ lập HĐ trên KK')),
                ('kieu', models.CharField(choices=[('TM', 'Tiền mặt'), ('CK', 'Chuyển khoản'), ('TMCK', 'Tiền mặt + CK'), ('DB', 'Đổi bù')], max_length=4)),
                ('tong', models.DecimalField(decimal_places=0, max_digits=18)),
                ('tien_mat', models.DecimalField(decimal_places=0, max_digits=18)),
                ('chuyen_khoan', models.DecimalField(decimal_places=0, max_digits=18)),
                ('ck_nhan', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='CK đã nhận (bank_notifications)')),
                ('ck_so_lan', models.PositiveSmallIntegerField(default=0)),
                ('nhan_vien', models.CharField(blank=True, default='', max_length=200)),
                ('khach', models.CharField(blank=True, default='', max_length=200)),
                ('nguoi_kiem', models.CharField(max_length=150)),
                ('kiem_luc', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Check bill',
                'db_table': 'check_bill',
                'ordering': ['-kiem_luc'],
            },
        ),
    ]
