# Generated by Django 5.2.17 on 2026-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0040_check_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldCheckEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(db_index=True, verbose_name='Ngày kiểm')),
                ('product_code', models.CharField(db_index=True, max_length=30, verbose_name='Mã sản phẩm')),
                ('gold_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Loại vàng')),
                ('product_desc', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên sản phẩm')),
                ('total_weight', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Trọng lượng (KK, chi × 100)')),
                ('nhan_vien', models.CharField(blank=True, default='', max_length=150, verbose_name='NV kiểm')),
                ('quet_luc', models.DateTimeField(auto_now_add=True, verbose_name='Giờ quét')),
                ('go_luc', models.DateTimeField(blank=True, null=True, verbose_name='Giờ gỡ khỏi danh sách')),
                ('go_boi', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Kiểm vàng',
                'verbose_name_plural': 'Kiểm vàng',
                'db_table': 'gold_check_entry',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('ngay', 'product_code'), name='uq_gold_check_ngay_ma')],
            },
        ),
    ]
