# Generated by Django 5.2.17 on 2026-09-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0041_check_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyflow',
            name='cus_cash',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Tiền mặt khách đưa'),
        ),
        migrations.AddField(
            model_name='moneyflow',
            name='cus_change',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Tiền thừa trả khách'),
        ),
    ]
