# Generated by Django 5.2.17 on 2026-09-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0042_money_flow_cus_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldCheckMoc',
            fields=[
                ('flow_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Dòng money_flow')),
                ('xong_luc', models.DateTimeField(blank=True, null=True, verbose_name='Lúc xong')),
                ('noi_bat_luc', models.DateTimeField(blank=True, null=True, verbose_name='Lúc bắt đầu nổi bật')),
                ('tao_luc', models.DateTimeField(auto_now_add=True, verbose_name='Lần đầu thấy')),
            ],
            options={
                'verbose_name': 'Mốc thẻ CHECK GOLD',
                'verbose_name_plural': 'Mốc thẻ CHECK GOLD',
                'db_table': 'gold_check_moc',
            },
        ),
    ]
